# Generated by Django 3.0 on 2019-12-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfilemodel',
            name='title',
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='user',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
